version: "3"
services:
  tester:
    image: shawnseabrook/build:|BUILD|
    depends_on: "server"
    command: ["RunTests.exe"]
  server:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"